# Generated by Django 5.2.5 on 2025-08-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='tipo_usuario',
            field=models.IntegerField(),
        ),
    ]
