# Generated by Django 5.2.5 on 2025-08-22 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_usertype_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='subServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subservicio', models.CharField(max_length=100)),
                ('id_servcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
        ),
    ]
