# Generated by Django 5.2.5 on 2025-08-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_subservices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subservices',
            old_name='id_servcio',
            new_name='id_servicio',
        ),
    ]
